rabbit:
  image: southsidesoft/rabbitmq
  ports:
  - 15672:15672
  - 5672:5672
  environment:
  - RABBITMQ_NODENAME=rabbit
search:
  image: southsidesoft/elasticsearch
  ports:
  - 9200:9200
  - 9300:9300
  # If you turn on config, you also have to setup a config file
  volumes:
  - $PWD/mydata:/usr/share/elasticsearch/data
  #- $PWD/config:/usr/share/elasticsearch/config
